version: "3"
services:
  node:
    build: .
    command: "npm run dev"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      expose:
        - "3001"
      ports:
        - "3001:3001"